import { getAttributeFromDOM } from './utils.js';

const AGE_RESTRICTION_ERROR_ENDPOINT = '/agerestrictionerror';
const CHOICE_NOT_SAVED_ENDPOINT = '/choicenotsaved';
const CONFIRMATION_DELIVERY_METHOD_ENDPOINT ='/confirmationdeliverymethod';
const CONFIRMATION_SENDER_ENDPOINT = '/confirmationsender';
const CONTACT_DETAILS_NOT_FOUND_ENDPOINT = '/contactdetailsnotfound';
const CONTACT_DETAILS_NOT_RECOGNISED_ENDPOINT = '/contactdetailsnotrecognised';
const COOKIE_POLICY_ENDPOINT = '/cookiespolicy';
const CREATE_SESSION_ENDPOINT = '/createsession';
const DETAILS_ENDPOINT = '/details';
const ENTER_PASSWORD_ENDPOINT = '/enterpassword';
const ENTER_YOUR_CODE_ENDPOINT = '/enteryourcode';
const EXPIRED_CODE_ERROR_ENDPOINT = '/expiredcodeerror';
const GENERIC_SYSTEM_ERROR_ENDPOINT = '/genericerror';
const GET_PREFERENCE_RESULT_ENDPOINT = '/getpreferenceresult';
const INCORRECT_CODE_ERROR_ENDPOINT = '/incorrectcodeerror';
const INCORRECT_PASSWORD_ERROR_ENDPOINT = '/incorrectpassworderror';
const LANDING_PAGE_ENDPOINT = '/landingpage';
const LOOKUP_FAILURE_ERROR_ENDPOINT = '/lookupfailureerror';
const OTHER_WAYS_TO_SET_YOUR_PREFERENCES_ENDPOINT = getAttributeFromDOM('data-other-ways-endpoint');
const PATIENT_SEARCH_RESULT_ENDPOINT = '/patientsearchresult';
const PRIVACY_NOTICE_ENDPOINT = '/privacynotice';
const QUOTE_EXCEEDED_ENDPOINT = '/quotaexceeded';
const REQUEST_CODE_ENDPOINT = '/requestcode';
const RESEND_CODE_ENDPOINT = '/resendcode';
const RESEND_CODE_ERROR_ENDPOINT = '/resendcodeerror';
const REVIEW_YOUR_CHOICE_ENDPOINT ='/reviewyourchoice';
const SERVICE_UNAVAIABLE_ENDPOINT = '/serviceunavailable';
const SESSION_EXPIRED_ENDPOINT = '/sessionexpired';
const SET_PREFERENCES_ENDPOINT = '/setpreferences';
const SET_YOUR_PREFERENCES_ENDPOINT = '/setyourpreferences';
const STATIC_RESOURCES_CDN_ENDPOINT = getAttributeFromDOM('data-static-resources-cdn');
const STORE_PREFERENCES_RESULT_ENDPOINT = '/storepreferencesresult';
const THANK_YOU_ENDPOINT = '/thankyou';
const VERIFICATION_OPTION_ENDPOINT = '/verificationoption';
const VERIFY_CODE_ENDPOINT = '/verifycode';
const VERIFY_PASSWORD_ENDPOINT = '/verifypassword';
const YOUR_DETAILS_ENDPOINT = '/yourdetails';


export {
  AGE_RESTRICTION_ERROR_ENDPOINT,
  CHOICE_NOT_SAVED_ENDPOINT,
  CONFIRMATION_DELIVERY_METHOD_ENDPOINT,
  CONFIRMATION_SENDER_ENDPOINT,
  CONTACT_DETAILS_NOT_FOUND_ENDPOINT,
  CONTACT_DETAILS_NOT_RECOGNISED_ENDPOINT,
  COOKIE_POLICY_ENDPOINT,
  CREATE_SESSION_ENDPOINT,
  DETAILS_ENDPOINT,
  ENTER_PASSWORD_ENDPOINT,
  ENTER_YOUR_CODE_ENDPOINT,
  EXPIRED_CODE_ERROR_ENDPOINT,
  GENERIC_SYSTEM_ERROR_ENDPOINT,
  GET_PREFERENCE_RESULT_ENDPOINT,
  INCORRECT_CODE_ERROR_ENDPOINT,
  INCORRECT_PASSWORD_ERROR_ENDPOINT,
  LANDING_PAGE_ENDPOINT,
  LOOKUP_FAILURE_ERROR_ENDPOINT,
  OTHER_WAYS_TO_SET_YOUR_PREFERENCES_ENDPOINT,
  PATIENT_SEARCH_RESULT_ENDPOINT,
  PRIVACY_NOTICE_ENDPOINT,
  QUOTE_EXCEEDED_ENDPOINT,
  REQUEST_CODE_ENDPOINT,
  RESEND_CODE_ENDPOINT,
  RESEND_CODE_ERROR_ENDPOINT,
  REVIEW_YOUR_CHOICE_ENDPOINT,
  SERVICE_UNAVAIABLE_ENDPOINT,
  SESSION_EXPIRED_ENDPOINT,
  SET_PREFERENCES_ENDPOINT,
  SET_YOUR_PREFERENCES_ENDPOINT,
  STORE_PREFERENCES_RESULT_ENDPOINT,
  STATIC_RESOURCES_CDN_ENDPOINT,
  THANK_YOU_ENDPOINT,
  VERIFICATION_OPTION_ENDPOINT,
  VERIFY_CODE_ENDPOINT,
  VERIFY_PASSWORD_ENDPOINT,
  YOUR_DETAILS_ENDPOINT
};
